name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    # runner provided by github workflow
    runs-on: [ubuntu-latest] 
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        # skipping the tests
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t aryasah30/paypilot .
      - name: Publish image to docker hub
        run: docker push aryasah30/paypilot:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Start Docker (if not running)
        run: sudo service docker start
      - name: Pull Image from docker hub
        run: docker pull aryasah30/paypilot:latest
      - name: Delete old container
        run: docker rm -f paypilot-container || true
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name paypilot-container aryasah30/paypilot

        